services:
  - postgresql
language: ruby
rvm:
  - "2.3.5"
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rake /
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
bundler_args: --binstubs=./bundler_stubs
